name: Master

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prettify code
      uses: creyD/prettier_action@v4.3
      with:
        prettier_options: --write **/*.json
        same_commit: true

    - name: Install jq
      run: sudo apt-get install jq

    - name: Generate UUIDs
      id: generate_uuids
      run: |
        HEADER_UUID=$(uuidgen)
        MODULE_UUID=$(uuidgen)
        echo "HEADER_UUID=$HEADER_UUID" >> $GITHUB_ENV
        echo "MODULE_UUID=$MODULE_UUID" >> $GITHUB_ENV

    - name: Update manifest.json
      run: |
        jq --arg header_uuid "$HEADER_UUID" --arg module_uuid "$MODULE_UUID" \
        '.header.uuid = $header_uuid | .modules[0].uuid = $module_uuid' manifest.json > tmp.json && mv tmp.json manifest.json

    - name: Create archive
      run: zip -r pack.mcpack . -x ".git/*" ".github/*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: repository-archive
        path: pack.mcpack

    - name: Notify Discord
      uses: sarisia/actions-status-discord@v1.13.0
      if: always()
      continue-on-error: true
      with:
        webhook: ${{ secrets.LOG_HOOK }}
        title: Zip successful!
        nodetail: true
        notimestamp: true
        description: |
          Commit `${{ github.sha }}` by ${{ github.actor }}
          Click [here](https://nightly.link/NSPC911/High-Contrast-BE/actions/runs/${{ github.run_id }}) to download!
        avatar_url: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
        username: "NSPC911/High-Contrast-BE"
